# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWorksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('score', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ('partner', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='CreditOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rotation_from', models.DateTimeField()),
                ('rotation_to', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('offer_type', models.PositiveSmallIntegerField(choices=[(1, 'Consumer'), (2, 'Hypothec'), (3, 'Auto loan')], default=1)),
                ('score_min', models.PositiveIntegerField(blank=True, default=0)),
                ('score_max', models.PositiveIntegerField(blank=True, default=0)),
                ('credit_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_list', to='offer.CreditOrganization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'Sent'), (2, 'Received'), (3, 'Approved'), (4, 'Denied'), (5, 'Issued')], default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_orders_list', to='offer.Offer')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders_list', to='offer.ClientWorksheet')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='clientworksheet',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets_list', to='offer.Partner'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('worksheet', 'offer')]),
        ),
    ]
