# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientworksheet',
            name='dob',
            field=models.DateField(),
        ),
    ]
